// Mock "System A" — a REST orders source.
//
// Pretends to be an external ERP / commerce backend that exposes a paginated
// orders feed. Integration code generated by the platform will poll this
// service via GET /orders?since=<ISO> and forward results into System B.
//
// Pure in-memory: ~50 fake orders generated at startup spread across the last
// 24 hours. POST /reset re-seeds.

import Fastify from "fastify";

type OrderItem = {
  sku: string;
  qty: number;
  price: number;
};

type Order = {
  id: string;
  customer: string;
  amount: number;
  currency: "USD";
  created_at: string; // ISO timestamp
  items: OrderItem[];
};

const CUSTOMERS = [
  "Acme Corp",
  "Globex",
  "Initech",
  "Umbrella",
  "Stark Industries",
  "Wayne Enterprises",
  "Soylent",
  "Cyberdyne",
  "Tyrell Corp",
  "Hooli",
];

const SKUS = [
  "WIDGET-001",
  "WIDGET-002",
  "GADGET-A",
  "GADGET-B",
  "DOODAD-X",
  "THINGAMAJIG-1",
  "WHATSIT-7",
];

function randomBetween(min: number, max: number): number {
  return Math.random() * (max - min) + min;
}

function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)]!;
}

function generateOrders(count: number): Order[] {
  const now = Date.now();
  const dayMs = 24 * 60 * 60 * 1000;
  const orders: Order[] = [];
  for (let i = 0; i < count; i++) {
    // Spread created_at across the last 24h.
    const offset = Math.floor(randomBetween(0, dayMs));
    const created = new Date(now - offset).toISOString();
    const itemCount = Math.floor(randomBetween(1, 5));
    const items: OrderItem[] = [];
    let amount = 0;
    for (let j = 0; j < itemCount; j++) {
      const qty = Math.floor(randomBetween(1, 6));
      const price = Math.round(randomBetween(5, 250) * 100) / 100;
      items.push({ sku: pick(SKUS), qty, price });
      amount += qty * price;
    }
    orders.push({
      id: `ord_${i.toString().padStart(5, "0")}_${Math.random().toString(36).slice(2, 8)}`,
      customer: pick(CUSTOMERS),
      amount: Math.round(amount * 100) / 100,
      currency: "USD",
      created_at: created,
      items,
    });
  }
  // Sort by created_at ascending so the cursor pagination works naturally.
  orders.sort((a, b) => a.created_at.localeCompare(b.created_at));
  return orders;
}

let ORDERS: Order[] = generateOrders(50);

const PORT = Number(process.env.PORT ?? process.env.MOCK_SYSTEM_A_PORT ?? 5001);
const HOST = "0.0.0.0";

export function buildServer() {
  const app = Fastify({ logger: { level: process.env.LOG_LEVEL ?? "info" } });

  app.get("/health", async () => ({ status: "ok" }));

  app.get<{ Querystring: { since?: string } }>(
    "/orders",
    async (req) => {
      const since = req.query.since;
      // Filter strictly after the cursor when provided. If absent, return the
      // earliest 10 orders. Always sorted asc by created_at, capped at 10.
      const filtered = since
        ? ORDERS.filter((o) => o.created_at > since)
        : ORDERS.slice();
      return filtered.slice(0, 10);
    },
  );

  app.post("/reset", async () => {
    ORDERS = generateOrders(50);
    return { ok: true, count: ORDERS.length };
  });

  return app;
}

// Only auto-listen when invoked directly, so tests can import buildServer().
const isMain = import.meta.url === `file://${process.argv[1]}`;
if (isMain) {
  const app = buildServer();
  app
    .listen({ port: PORT, host: HOST })
    .then(() => {
      app.log.info(`mock-system-a listening on ${HOST}:${PORT}`);
    })
    .catch((err) => {
      app.log.error(err);
      process.exit(1);
    });
}
